---

# Database

- name: Create database user.
  sudo_user: postgres
  postgresql_user: name={{ studentenportal_db_user }} password={{ studentenportal_db_pass }}
    role_attr_flags=CREATEDB

- name: Create database.
  sudo_user: postgres
  postgresql_db: name={{ studentenportal_db }} owner={{ studentenportal_db_user }}
    encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template1'
